#!/usr/bin/env tsx
/**
 * 90-pm-investing-deep.ts
 *
 * Persona-specific deep research for 90s.PM.Investing (TWITTER_CRYPTO).
 * Auto-generated by `0_scaffold/scaffold.ts`.
 *
 * Features:
 * - Search-driven source discovery (6 layers)
 * - Era-segmented deep research (3 eras)
 * - Adversarial + decision-record search queries
 * - Source classification with trust weights
 *
 * Usage:
 *   npx tsx ../personas-deep-research/90-pm-investing-deep.ts
 */

import { deepResearch, searchFirecrawl } from "../firecrawl-research.js";
import { discoverSources } from "../firecrawl-discovery.js";
import { writeFileSync, mkdirSync } from "fs";

const FIRECRAWL_KEY = process.env.VITE_FIRECRAWL_API_KEY!;
const TIMESTAMP = new Date().toISOString().slice(0, 10);
const OUT_DIR = "../../data";
const NAME = "90s.PM.Investing";
const ID = "90-pm-investing";

mkdirSync(OUT_DIR, { recursive: true });

async function main() {
  if (!FIRECRAWL_KEY) {
    console.error("VITE_FIRECRAWL_API_KEY not set");
    process.exit(1);
  }

  console.log("\u{1F4AC} Deep research for " + NAME + "...");
  console.log("");

  // Phase 0: Source discovery (6 layers)
  console.log("=== Phase 0: Search-Driven Discovery ===");
  try {
    const discResult = await discoverSources(NAME, "TWITTER_CRYPTO", { maxQueries: 15 });
    console.log("  \u2705 " + discResult.totalSources + " sources discovered across 6 layers");
    writeFileSync(
      OUT_DIR + "/discovery-" + ID + "-" + TIMESTAMP + ".json",
      JSON.stringify(discResult, null, 2)
    );
    for (const gap of discResult.metadata.coverageGaps) {
      console.log("  \u26A0  " + gap);
    }
    const targets = discResult.priorityScrapeTargets.slice(0, 12);
    console.log("  \u{1F3AF} Priority targets: " + targets.length);
    writeFileSync(
      OUT_DIR + "/scrape-targets-" + ID + "-" + TIMESTAMP + ".json",
      JSON.stringify(targets, null, 2)
    );
  } catch (e: any) {
    console.warn("  \u26A0  Discovery failed: " + e.message);
  }
  console.log("");

  // Phase 1: Era-segmented deep research
  console.log("=== Phase 1: Era-Segmented Deep Research ===");
  const eraQueries = [
      {
        era: "1-Early",
        topic: "90s.PM.Investing early crypto trading first posts methodology formation",
        recencyDays: 7300,
        limit: 12
      },
      {
        era: "2-Growth",
        topic: "90s.PM.Investing trading career growth competitive positioning key trades",
        recencyDays: 3650,
        limit: 12
      },
      {
        era: "3-Recent",
        topic: "90s.PM.Investing recent positions commentary current strategy market analysis",
        recencyDays: 1095,
        limit: 15
      }
  ];
  for (const q of eraQueries) {
    console.log("  \u{1F4E1} [" + q.era + "] " + q.topic.slice(0, 50) + "...");
    try {
      const result = await deepResearch(FIRECRAWL_KEY, q.topic, {
        recencyDays: q.recencyDays,
        limit: q.limit,
      });
      writeFileSync(
        OUT_DIR + "/deep-" + ID + "-" + q.era + "-" + TIMESTAMP + ".json",
        JSON.stringify(result, null, 2)
      );
      const sources = result.data?.sources?.length || 0;
      console.log("  \u2705 [" + q.era + "] Deep research \u2014 " + sources + " sources");
    } catch (e: any) {
      console.warn("  \u26A0  [" + q.era + "] Failed: " + e.message);
    }
    await new Promise(r => setTimeout(r, 3000));
  }
  console.log("");

  // Phase 2: Adversarial + decision-record search
  const adversarialQueries = [
  { category: "adversarial", query: "\"90s.PM.Investing\" criticism OR scandal OR failure OR mistake OR lawsuit" },
  { category: "adversarial", query: "\"90s.PM.Investing\" investigation OR SEC OR regulatory OR fraud OR accused" },
  { category: "decision-records", query: "\"90s.PM.Investing\" acquisition OR investment OR key decision reasoning" }
  ];
  if (adversarialQueries.length > 0) {
    console.log("=== Phase 2: Adversarial + Decision Records ===");
    for (const q of adversarialQueries) {
      console.log("  \u{1F50D} [" + q.category + "] " + q.query.slice(0, 60) + "...");
      try {
        const result = await searchFirecrawl(FIRECRAWL_KEY, q.query, 10);
        console.log("  \u2705 " + (result.data?.length || 0) + " results");
        writeFileSync(
          OUT_DIR + "/search-" + ID + "-" + q.category + "-" + TIMESTAMP + ".json",
          JSON.stringify(result, null, 2)
        );
      } catch (e: any) {
        console.warn("  \u26A0  " + e.message);
      }
      await new Promise(r => setTimeout(r, 2000));
    }
  }

  console.log("");
  console.log("\u2705 Deep research complete. Files in " + OUT_DIR + "/");
}

main().catch(console.error);